# Git aliases
alias gst="git status"
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias gl="git log --oneline"
alias gd="git diff"
alias gds="git diff --staged"
alias gfa="git fetch --all --tags --prune"
alias gup="git pull --rebase"
alias grs="git restore"
alias grst="git restore --staged"
